---
title: "Week 5 code along_penguin size"
author: "Joaquin Meckler"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(effsize)
library(broom)
library(ggbeeswarm)
library(car)
```

## T-Tests

mass: comparison between male and female penguins

```{r}
chinstrap<-penguins %>% 
  filter(species=="Chinstrap")

# Histograms

ggplot(data=chinstrap, aes(x=body_mass_g))+
  geom_histogram(bins=10)+
  facet_wrap(~sex)

# QQ plot

ggplot(data=chinstrap, aes(sample = body_mass_g))+
  geom_qq()+
  facet_wrap(~sex)

# discriptive statistics

chinstrap %>% 
  group_by(sex) %>% 
  summarize(
    mean_mass=mean(body_mass_g),
    median_mass=median(body_mass_g),
    sd_mass=sd(body_mass_g),
    sample_size=n()
  )
```

get vectors of body_mass_g for M/F

```{r}
chinstrap_f<-chinstrap %>% 
  filter(sex== "female") %>% 
  pull(body_mass_g)


chinstrap_m<-chinstrap %>% 
  filter(sex== "male") %>% 
  pull(body_mass_g)
```

### 2 sample T test

1. is there a significant difference between male and female body mass?

```{r}
chinstrap_ttest<-t.test(chinstrap_f, chinstrap_m)

chinstrap_ttest

cohen.d(chinstrap_f, chinstrap_m)
```


are male chinstraps significantly larger then female chinstraps

```{r}
t.test(chinstrap_m,chinstrap_f, alternative = "greater")
```














